import Head from "next/head";
import Image from "next/image";
// import { addToCart } from "@bable/redux/features/cartSlice";
import { useDispatch } from "react-redux";
import { HiOutlineEye } from "react-icons/hi";
import { AiOutlineHeart } from "react-icons/ai";
import PaymentLogo from "../../components/assets/payment-logo.webp";
import {
  addToCart,
  clearCart,
  decreaseCart,
  getTotals,
  removeFromCart,
} from "@bable/redux/features/cartSlice";

const Product = ({ product }) => {
  const dispatch = useDispatch();
  const handleAdd = (product) => {
    dispatch(addToCart(product));
  };

  const handleRemove = (cartItem) => {
    dispatch(removeFromCart(cartItem));
  };
  const handleAddToCart = (cartItem) => {
    dispatch(addToCart(cartItem));
  };
  const handleDecreaseCart = (cartItem) => {
    dispatch(decreaseCart(cartItem));
  };
  return (
    <>
      <Head>
        <title>{product.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-1 lg:grid-cols-2 ml-4 lg:mx-36">
          <div className="flex items-center justify-center">
            <div className="hidden md:flex md:flex-row">side image</div>
            <Image
              src={product.image}
              style={{ width: "70%" }}
              width={600}
              height={450}
              alt="image"
            />
          </div>
          <div className="">
            <p className="flex items-center">
              {" "}
              <HiOutlineEye className="text-red-600" />{" "}
              <span className="text-red-600 font-medium py-2 font-['Jost'] ml-2 text-lg">
                37 guests
              </span>{" "}
              <span className="ml-2 font-medium font-['Jost'] text-lg py-2">
                are viewing this product
              </span>{" "}
            </p>
            <h3 className="text-4xl font-['Jost'] text-[#111111] mb-1 font-normal">
              {product.title}
            </h3>
            <h5 className="text-4xl font-['Jost'] text-[#111111] mb-1 font-normal">
              RS.{product.price}
            </h5>
            <p className="font-normal font-['Jost'] my-3 text-[#555555] text-2xl">
              Size:
            </p>
            <div className="flex">
              <button className="px-3 border border-[#ddd] text-base py-3 mx-1">
                L
              </button>
              <button className="px-3 border border-[#ddd] text-base py-3 mx-1">
                M
              </button>
              <button className="px-3 border border-[#ddd] text-base py-3 mx-1">
                S
              </button>
              <button className="px-3 border border-[#ddd] text-base py-3 mx-1">
                XL
              </button>
            </div>
            <p className="mt-2">Quantity</p>
            <div className="grid md:grid-cols-4">
              <div className="flex items-center px-3 py-6 my-4 border rounded-md border-[#ddd] text-base w-36 justify-between lg:mr-8 h-10">
                <button
                  className="text-md font-bold w-5 h-4 mx-3"
                  onClick={() => handleDecreaseCart(product)}
                >
                  -
                </button>
                <div className="text-md font-bold ml-3 font-['Jost'] w-5 h-4 -pt-4">
                  {/* {cartItem.cartQuantity} */}
                </div>
                <button
                  className="text-md font-bold w-5 h-4 mx-3"
                  onClick={() => handleAddToCart(product)}
                >
                  +
                </button>
              </div>
              <button
                className="px-3 py-3 lg:ml-2 font-['Jost'] text-sm leading-[18px] font-bold rounded-md my-4 bg-black text-white mx-2"
                onClick={() => handleAdd(product)}
              >
                Add to cart
              </button>
              <button className="px-3 font-['Jost'] text-sm leading-[18px] font-bold rounded-md py-3 my-4 bg-[#C8815F] text-white mx-2">
                Buy Now
              </button>
              <p className="px-3 rounded-md py-3 my-4">
                <AiOutlineHeart className="w-6 h-6" />
              </p>
            </div>
            <div className="flex flex-col xl:flex-row bg-[#FBFBF9] my-6 py-5 rounded items-start xl:items-center">
              <p>Secure checkout with</p>
              <Image
                src={PaymentLogo}
                width={300}
                height={210}
                alt="checkout method"
                className="ml-0"
              />
            </div>
            <p className="font-['Jost'] font-light my-3 text-[#555555] text-lg">
              Free shipping over $300
            </p>
            <p className="font-normal font-['Jost'] my-3 text-[#555555] text-lg">
              SKU:
            </p>
            <p className="font-normal font-['Jost'] my-3 text-[#555555] text-lg">
              Categories:{" "}
              <span className="font-normal font-['Jost'] my-3 text-[#555555] text-lg">
                {product.category}
              </span>{" "}
            </p>
            <p>share</p>
          </div>
        </div>
      </main>
    </>
  );
};

export async function getServerSideProps({ params: { id } }) {
  const res = await fetch(`https://fakestoreapi.com/products/${id}`);
  const data = await res.json();
  return {
    props: { product: data },
  };
}

export default Product;
