import Head from "next/head";
import ProductCard from "@bable/components/components/Products/ProductCard";

const category = ({ products }) => {
  
  return (
    <>
     <Head>
        <title>{products[0].category}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
      <div className="container mx-auto ">
              <div className="grid items-center grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6 max-w-sm mx-auto md:max-w-none md:mx-auto justify-between">
                {products.map((product) => (
                  <ProductCard key={product.id} product={product} />
                ))}
              </div>
            </div>
      </section>
    
    </>
 
  )
}


export async function getServerSideProps({ params: { category } }) {
    const res = await fetch(`https://fakestoreapi.com/products`);
    
    const data = await res.json();
    // console.log(data)
    const newData = data.filter(function (item) {
        return item.category == category
    })
    console.log(newData)
    return {
      props: { products: newData },
      
    };
  }

export default category;